-- ═══════════════════════════════════════════════════════════════
-- OBSOLET — NO EXECUTIS AQUEST FITXER
--
-- Aquesta versió instal·lava les taules a l'esquema `public`. Com que
-- el projecte de Supabase es comparteix amb IntraNex, tot ha passat a
-- un esquema propi anomenat `comunitat`.
--
-- Executar això sobreescriuria funcions d'IntraNex (set_updated_at)
-- i podria trencar el CRM.
--
--   →  Fes servir  api/schema-full.sql
--
-- Es manté el fitxer perquè els ZIP no poden esborrar; es pot eliminar
-- del repositori sense cap problema.
-- ═══════════════════════════════════════════════════════════════
