-- Comunitat NexSocial · dades inicials d'activitats
-- Generat des de js/data.js. Opcional: nomes si vols gestionar
-- les activitats des del panel en lloc de data.js.
-- Es pot re-executar: actualitza les que ja existeixen.

insert into public.events (id, tipo, titol, descripcio, entitat, ubicacio, mapa_url, data, hora, durada, data_label, cupo, preu_cents, tipo_iva, imatge, imatge_lloc, estat) values
  ('passejada-badalona-2026-10', 'mensual', '{"ca":"Passejades a l''aire lliure","es":"Paseos al aire libre"}'::jsonb, '{"ca":"Passejades tranquil·les i itinerants pel litoral de Badalona. Cada mes canviem l''itinerari per descobrir plegats el barri, l''aire lliure i la companyia. Ritme adaptat, pauses les que calguin.","es":"Paseos tranquilos e itinerantes por el litoral de Badalona. Cada mes cambiamos el itinerario para descubrir juntas el barrio, el aire libre y la compañía. Ritmo adaptado, pausas las que hagan falta."}'::jsonb, '{"ca":"NexSocial","es":"NexSocial"}'::jsonb, '{"ca":"Punt de trobada: Fàbrica Anís del Mono, Badalona","es":"Punto de encuentro: Fábrica Anís del Mono, Badalona"}'::jsonb, 'https://maps.google.com/?q=F%C3%A0brica+Anis+del+Mono+Badalona', '2026-10-05', '10:30', 90, '{"ca":"Octubre 2026","es":"Octubre 2026"}'::jsonb, 20, 0, 'exempt', '/assets/passeig.jpg', '/assets/passeig.jpg', 'actiu'),
  ('vivioteca-2026-10', 'mensual', '{"ca":"Vivioteca · Trobada mensual","es":"Vivioteca · Encuentro mensual"}'::jsonb, '{"ca":"Trobada mensual per compartir vivències, lectures i experiències. Un espai relaxat per parlar, escoltar i teixir vincle.","es":"Encuentro mensual para compartir vivencias, lecturas y experiencias. Un espacio relajado para hablar, escuchar y tejer vínculo."}'::jsonb, '{"ca":"NexSocial · Casal Centre","es":"NexSocial · Casal Centre"}'::jsonb, '{"ca":"Casal de Gent Gran Centre, Badalona","es":"Casal de Gent Gran Centre, Badalona"}'::jsonb, 'https://maps.google.com/?q=Casal+Gent+Gran+Centre+Badalona', '2026-10-15', '17:00', 90, '{"ca":"Octubre 2026","es":"Octubre 2026"}'::jsonb, 25, 0, 'exempt', '/assets/vivioteca.jpg', '/assets/casal-centre.jpg', 'actiu'),
  ('tablao-canyado-2026-10', 'esdeveniment', '{"ca":"Tablao Flamenc a Canyadó","es":"Tablao Flamenco en Canyadó"}'::jsonb, '{"ca":"Vetllada de flamenc en directe al barri de Canyadó. Guitarra, cant i ball en un espai íntim. Aforament limitat.","es":"Velada de flamenco en directo en el barrio de Canyadó. Guitarra, cante y baile en un espacio íntimo. Aforo limitado."}'::jsonb, '{"ca":"NexSocial · Canyadó","es":"NexSocial · Canyadó"}'::jsonb, '{"ca":"Local del barri de Canyadó, Badalona","es":"Local del barrio de Canyadó, Badalona"}'::jsonb, 'https://maps.google.com/?q=Canyad%C3%B3+Badalona', '2026-10-24', '18:30', 90, '{"ca":"Pròximament","es":"Próximamente"}'::jsonb, 40, 1000, 'iva10', '/assets/flamenco.jpg', '/assets/flamenco.jpg', 'proximament'),
  ('taller-emocional-centre', 'taller', '{"ca":"Taller d''acompanyament emocional","es":"Taller de acompañamiento emocional"}'::jsonb, '{"ca":"Espai per compartir com estem, aprendre eines per gestionar emocions i teixir xarxa amb altres persones del barri. Grup reduït.","es":"Espacio para compartir cómo estamos, aprender herramientas para gestionar emociones y tejer red con otras personas del barrio. Grupo reducido."}'::jsonb, '{"ca":"Casal de Gent Gran Centre (ASJP)","es":"Casal de Gent Gran Centre (ASJP)"}'::jsonb, '{"ca":"Casal Centre, Badalona","es":"Casal Centre, Badalona"}'::jsonb, 'https://maps.google.com/?q=Casal+Gent+Gran+Centre+Badalona', '2026-09-15', '17:00', 90, '{"ca":"Setembre 2026","es":"Septiembre 2026"}'::jsonb, 15, 0, 'exempt', '/assets/taller-emocional.jpg', '/assets/casal-centre.jpg', 'proximament'),
  ('taller-mobil-centre', 'taller', '{"ca":"Taller de mòbil bàsic","es":"Taller de móvil básico"}'::jsonb, '{"ca":"Aprèn a fer servir el mòbil sense por: trucades, WhatsApp, càmera, cita al metge... Va al teu ritme.","es":"Aprende a usar el móvil sin miedo: llamadas, WhatsApp, cámara, cita médica... A tu ritmo."}'::jsonb, '{"ca":"Casal de Gent Gran Centre (ASJP)","es":"Casal de Gent Gran Centre (ASJP)"}'::jsonb, '{"ca":"Casal Centre, Badalona","es":"Casal Centre, Badalona"}'::jsonb, 'https://maps.google.com/?q=Casal+Gent+Gran+Centre+Badalona', '2026-09-17', '17:00', 90, '{"ca":"Setembre 2026","es":"Septiembre 2026"}'::jsonb, 12, 0, 'exempt', '/assets/taller-mobil.jpg', '/assets/casal-centre.jpg', 'proximament'),
  ('taller-autodefensa-canpepus', 'taller', '{"ca":"Taller d''autodefensa","es":"Taller de autodefensa"}'::jsonb, '{"ca":"Recursos pràctics per sentir-nos més segures al carrer i a casa. Postura, veu, tècniques bàsiques i confiança.","es":"Recursos prácticos para sentirnos más seguras en la calle y en casa. Postura, voz, técnicas básicas y confianza."}'::jsonb, '{"ca":"Casal de la Solidaritat Can Pepus","es":"Casal de la Solidaritat Can Pepus"}'::jsonb, '{"ca":"Can Pepus, Raval (Badalona)","es":"Can Pepus, Raval (Badalona)"}'::jsonb, 'https://maps.google.com/?q=Casal+Can+Pepus+Badalona', '2026-09-22', '18:00', 90, '{"ca":"Setembre 2026","es":"Septiembre 2026"}'::jsonb, 15, 2500, 'exempt', '/assets/taller-autodefensa.jpg', '/assets/canpepus.jpg', 'proximament'),
  ('taller-angles-canpepus', 'taller', '{"ca":"Conversa en anglès","es":"Conversación en inglés"}'::jsonb, '{"ca":"Trobada setmanal per practicar l''anglès parlant, sense exàmens ni deures. Comencem pel que ja saps i anem fent. L''important és perdre la vergonya i passar-ho bé. Grup estable: la plaça et queda reservada per a totes les sessions.","es":"Encuentro semanal para practicar el inglés hablando, sin exámenes ni deberes. Empezamos por lo que ya sabes y vamos haciendo. Lo importante es perder la vergüenza y pasarlo bien. Grupo estable: la plaza te queda reservada para todas las sesiones."}'::jsonb, '{"ca":"Casal de la Solidaritat Can Pepus","es":"Casal de la Solidaritat Can Pepus"}'::jsonb, '{"ca":"Can Pepus, Raval (Badalona)","es":"Can Pepus, Raval (Badalona)"}'::jsonb, 'https://maps.google.com/?q=Casal+Can+Pepus+Badalona', '2026-10-08', '18:00', 90, '{"ca":"Cada setmana","es":"Cada semana"}'::jsonb, 12, 0, 'exempt', '/assets/taller-idioma.jpg', '/assets/canpepus.jpg', 'proximament'),
  ('taller-autodefensa-santroc', 'taller', '{"ca":"Taller d''autodefensa","es":"Taller de autodefensa"}'::jsonb, '{"ca":"Recursos pràctics per sentir-nos més segures al carrer i a casa. Postura, veu, tècniques bàsiques i confiança.","es":"Recursos prácticos para sentirnos más seguras en la calle y en casa. Postura, voz, técnicas básicas y confianza."}'::jsonb, '{"ca":"Centre Cívic Sant Roc","es":"Centre Cívic Sant Roc"}'::jsonb, '{"ca":"Centre Cívic Sant Roc, Badalona","es":"Centre Cívic Sant Roc, Badalona"}'::jsonb, 'https://maps.google.com/?q=Centre+Civic+Sant+Roc+Badalona', '2026-09-24', '18:00', 90, '{"ca":"Setembre 2026","es":"Septiembre 2026"}'::jsonb, 15, 2500, 'exempt', '/assets/taller-autodefensa.jpg', '/assets/sant-roc.jpg', 'proximament'),
  ('taller-castellano-santroc', 'taller', '{"ca":"Taller de castellà bàsic","es":"Taller de castellano básico"}'::jsonb, '{"ca":"Espai per practicar castellà i guanyar autonomia al dia a dia. Adaptat i sense pressa.","es":"Espacio para practicar castellano y ganar autonomía en el día a día. Adaptado y sin prisa."}'::jsonb, '{"ca":"Centre Cívic Sant Roc","es":"Centre Cívic Sant Roc"}'::jsonb, '{"ca":"Centre Cívic Sant Roc, Badalona","es":"Centre Cívic Sant Roc, Badalona"}'::jsonb, 'https://maps.google.com/?q=Centre+Civic+Sant+Roc+Badalona', '2026-09-16', '17:00', 90, '{"ca":"Setembre 2026","es":"Septiembre 2026"}'::jsonb, 15, 0, 'exempt', '/assets/taller-idioma.jpg', '/assets/sant-roc.jpg', 'proximament'),
  ('taller-mobil-santroc', 'taller', '{"ca":"Taller de mòbil bàsic","es":"Taller de móvil básico"}'::jsonb, '{"ca":"Aprèn a fer servir el mòbil sense por: trucades, WhatsApp, càmera, cita al metge... Va al teu ritme.","es":"Aprende a usar el móvil sin miedo: llamadas, WhatsApp, cámara, cita médica... A tu ritmo."}'::jsonb, '{"ca":"Centre Cívic Sant Roc","es":"Centre Cívic Sant Roc"}'::jsonb, '{"ca":"Centre Cívic Sant Roc, Badalona","es":"Centre Cívic Sant Roc, Badalona"}'::jsonb, 'https://maps.google.com/?q=Centre+Civic+Sant+Roc+Badalona', '2026-09-18', '17:00', 90, '{"ca":"Setembre 2026","es":"Septiembre 2026"}'::jsonb, 12, 0, 'exempt', '/assets/taller-mobil.jpg', '/assets/sant-roc.jpg', 'proximament')
on conflict (id) do update set
  tipo = excluded.tipo, titol = excluded.titol, descripcio = excluded.descripcio,
  entitat = excluded.entitat, ubicacio = excluded.ubicacio, mapa_url = excluded.mapa_url,
  data = excluded.data, hora = excluded.hora, durada = excluded.durada,
  data_label = excluded.data_label, cupo = excluded.cupo, preu_cents = excluded.preu_cents,
  tipo_iva = excluded.tipo_iva, imatge = excluded.imatge,
  imatge_lloc = excluded.imatge_lloc, estat = excluded.estat;
